In [6]:
import pandas as pd
df = pd.DataFrame(
 {"a" : [4, 5, 6],
 "b" : [7, 8, 9],
 "c" : [10, 11, 12]},
 index = [1, 2,3])
df.head()

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [4]:
df=pd.DataFrame({"a":[4,5,6]},
index=[1,2,3])

df.head()

   a
1  4
2  5
3  6

In [7]:
pd.Series([3,4,5])

0    3
1    4
2    5
dtype: int64

In [22]:
df=pd.DataFrame({
    "name": ["Rasida","Rajiya","Ramjan"],
    "Grade":[4.0, 3.5, None]
})
df.head()

     name  Grade
0  Rasida    4.0
1  Rajiya    3.5
2  Ramjan    NaN

In [ ]:
df=pd.DataFrame({
    "name": ["Rasida","Rajiya","Ramjan"],
    "Grade":[4.0, 3.5, 3.0]
})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   Grade   3 non-null      float64
dtypes: float64(1), str(1)
memory usage: 180.0 bytes

In [15]:
df=pd.DataFrame({
    "name": ["Rasida","Rajiya","Ramjan"],
    "Grade":[4.0, 3.5, 3.0]
})
df.loc()

In [ ]:
df=pd.DataFrame({
    "name": ["Rasida","Rajiya","Ramjan"],
    "Grade":[4.0, 3.5, 3.0]
})
df.describe()

       Grade
count   3.00
mean    3.50
std     0.50
min     3.00
25%     3.25
50%     3.50
75%     3.75
max     4.00

In [19]:
df=pd.DataFrame({
    "name": ["Rasida","Rajiya","Ramjan"],
    "Grade":[4.0, 3.5, 3.0]
})
df.shape

(3, 2)

In [23]:
print(df)
df=df.dropna()
print(df)

     name  Grade
0  Rasida    4.0
1  Rajiya    3.5
2  Ramjan    NaN
     name  Grade
0  Rasida    4.0
1  Rajiya    3.5

In [26]:
df= df.fillna(3.0)
df

     name  Grade
0  Rasida    4.0
1  Rajiya    3.5

In [ ]:
df.filter(items=['name'])

     name
0  Rasida
1  Rajiya